### PR TITLE
Use React Tippy for dropdowns and tooltips

### LINKED ISSUE #643: Pipeline console "View stage as plain text" link is incorrect
### Jenkins and plugins versions report

Plugin version: 448.vdeeb_b_c328b_c2

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Example build: https://ci.jenkins.io/job/Plugins/job/git-plugin/job/master/1496/pipeline-console/

For each stage, select More actions > View stage as plain text.

### Expected Results

"View stage as plain text" should link to the log for that stage.

### Actual Results

Every "View stage as plain text" link links to the same stage log (I think it links to the stage that was initially loaded, which by default seems to be the last one).

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by lewisbirks**
Fixes #643. The issue was that the dropdown template elements were not being updated when the stage was changing.

The fix for this has been to use the [React Tippy library](https://github.com/atomiks/tippyjs-react) to render the dropdowns rather than passing the behaviour off to Behaviour.js.  
At the same time the tooltips component has also been updated to use this new library.

### Testing done

Manual testing

Before

https://github.com/user-attachments/assets/f763890a-99cd-4785-b833-b1bca79a2d13

After

https://github.com/user-attachments/assets/d531f651-bdb5-441f-a20c-77bc6b907823

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

File: src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx [hunk 1]
```diff
@@ -14,6 +14,25 @@ export default function StageDetails({ stage }: StageDetailsProps) {
     return null;
   }
 
+  const dropdownItems = useMemo(() => [
+    {
+      text: `Hello ${stage.id}`,
```
Comment (lewisbirks) [inline src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx:19]: remove debugging

File: src/main/frontend/common/components/dropdown.tsx [hunk 2]
```diff
@@ -17,6 +17,16 @@ export default function Dropdown({ items, disabled }: DropdownProps) {
...
 
+    const parentNode = buttonRef.current.parentNode;
+    if (!parentNode) {
+      return;
+    }
+
+    const existingTemplates = parentNode.querySelectorAll("template");
+    existingTemplates.forEach((template) => template.remove());
+
+    console.log("called on items", items)
```
Comment (lewisbirks) [inline src/main/frontend/common/components/dropdown.tsx:28]: remove debugging

File: src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx [hunk 3]
```diff
@@ -14,6 +14,67 @@ export default function StageDetails({ stage }: StageDetailsProps) {
     return null;
   }
 
+  const dropdownItems = useMemo(
```
Comment (janfaracik) [inline src/main/frontend/pipeline-console-view/pipeline-console/main/stage-details.tsx:17]: We don't need memoization here

**Review by janfaracik — APPROVED** [review]
