### PR TITLE
Convert blue ocean icons to jenkins icons for the pipeline graph

### LINKED ISSUE #11: Convert graph to use new Jenkins icons
Currently we're using the blue ocean icons, we should try use the new Jenkins ones

image

image

### LINKED ISSUE #173: New status icons not found
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375
OS: Linux - 5.10.0-19-amd64
---
ace-editor:1.1
analysis-model-api:10.17.0
ansicolor:1.0.2
ant:481.v7b_09e538fcca
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
blueocean:1.25.8
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.8
blueocean-commons:1.25.8
blueocean-config:1.25.8
blueocean-core-js:1.25.8
blueocean-dashboard:1.25.8
blueocean-display-url:2.4.1
blueocean-events:1.25.8
blueocean-git-pipeline:1.25.8
blueocean-github-pipeline:1.25.8
blueocean-i18n:1.25.8
blueocean-jira:1.25.8
blueocean-jwt:1.25.8
blueocean-personalization:1.25.8
blueocean-pipeline-api-impl:1.25.8
blueocean-pipeline-editor:1.25.8
blueocean-pipeline-scm-api:1.25.8
blueocean-rest:1.25.8
blueocean-rest-impl:1.25.8
blueocean-web:1.25.8
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.1-3
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-name-setter:2.2.0
build-timeout:1.24
build-token-root:151.va_e52fe3215fc
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.5
cloudbees-bitbucket-branch-source:791.vb_eea_a_476405b
cloudbees-folder:6.773.vd2dcc704ee7e
cobertura:1.17
code-coverage-api:3.2.0
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-27.vb_fa_3896786a_7
concurrent-step:1.0.0
conditional-buildstep:1.4.2
configurationslicing:430.v966357576543
credentials:1189.vf61b_a_5e2f62e
credentials-binding:523.vd859a_4b_122e6
dark-theme:255.v364936264de8
dashboard-view:2.447.vda_124dd35f11
data-tables-api:1.12.1-4
display-url-api:2.3.6
docker-commons:1.21
docker-workflow:528.v7c193a_0b_e67c
dtkit-api:3.0.2
durable-task:501.ve5d4fc08b0be
echarts-api:5.4.0-1
email-ext:2.92
external-monitor-job:203.v683c09d993b_9
extra-columns:1.25
favorite:2.4.1
file-parameters:205.vf6ce13b_e5dee
font-awesome-api:6.2.0-3
forensics-api:1.16.0
generic-webhook-trigger:1.85.2
git:4.12.1
git-changelog:3.24
git-client:3.12.1
git-forensics:1.11.0
git-server:99.va_0826a_b_cdfa_d
github:1.36.0
github-api:1.303-400.v35c2d8258028
github-branch-source:1695.v88de84e9f6b_9
greenballs:1.15.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
html5-notifier-plugin:1.5
htmlpublisher:1.31
instance-identity:116.vf8f487400980
ionicons-api:31.v4757b_6987003
jackson2-api:2.13.4.20221013-295.v8e29ea_354141
jakarta-activation-api:2.0.1-2
jakarta-mail-api:2.0.1-2
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-5
javax-mail-api:1.6.2-8
jaxb:2.3.7-1
jdk-tool:55.v1b_32b_6ca_f9ca
jenkins-design-language:1.25.8
jersey2-api:2.37-1
jira:3.8
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.15-2
jobConfigHistory:1183.v6e2785ff75e0
jquery-detached:1.2.1
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1153.v1c24f1a_d2553
ldap:2.12
lockable-resources:2.18
log-parser:2.2
login-theme:1.1
mailer:438.v02c7f0a_12fa_4
mapdb-api:1.0.9-28.vf251ce40855d
material-theme:0.5.2-rc100.6121925fe229
matrix-auth:3.1.5
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.20
mercurial:1260.vdfb_723cdcc81
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.9.1-44.v476733c11f82
mina-sshd-api-core:2.9.1-44.v476733c11f82
momentjs:1.1.1
okhttp-api:4.9.3-108.v0feda04578cf
pam-auth:1.10
phabricator-plugin:2.1.5
pipeline-build-step:2.18
pipeline-config-history:1.6
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-graph-view:126.vc84e8c9d6233
pipeline-groovy-lib:613.v9c41a_160233f
pipeline-input-step:456.vd8a_957db_5b_e9
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.27
pipeline-stage-step:296.v5f6908f017a_5
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.27
pipeline-utility-steps:2.13.0
plain-credentials:139.ved2b_9cf7587b
plugin-util-api:2.18.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
prism-api:1.29.0-1
project-description-setter:1.2
pubsub-light:1.17
rebuild:1.34
run-condition:1.5
scm-api:621.vda_a_b_055e58f7
script-security:1189.vb_a_b_7c8fd5fde
sidebar-link:2.2.0
simple-queue:1.4.3
simple-theme-plugin:136.v23a_15f86c53d
snakeyaml-api:1.32-86.ve3f030a_75631
solarized-theme:0.1
sse-gateway:1.26
ssh-credentials:305.v8f4381501156
ssh-slaves:2.854.v7fd446b_337c9
sshd:3.249.v2dc2ea_416e33
structs:324.va_f5d6774f3a_d
theme-manager:1.5
timestamper:1.20
token-macro:308.v4f2b_ed62b_b_16
trilead-api:2.72.v2a_3236754f73
variant:59.vf075fe829ccb
warnings-ng:9.20.1
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1200.v8005c684b_a_c6
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:2803.v1a_f77ffcc773
workflow-durable-task-step:1210.va_1e5d77e122b
workflow-job:1249.v7d974144cc14
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
xunit:3.1.2

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian bullseye

### Reproduction steps

1. Open any pipeline graph
2. New status icons not found and not visible

### Expected Results

Status icons displayed

### Actual Results

Status icons not found

### Anything else?

After merging #167 the new status icons are not displayed on our instance.
In the browser log I can see that the plugin tries to load the status sprite from ``https://XXX/jenkins/images/build-status/build-status-sprite.svg`` but it actually is found under ``https://XXX/images/build-status/build-status-sprite.svg``.

Is this some kind of configuration issue regarding resources on our instance or should this (https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx#L16) be changed?

### PR DESCRIPTION
**Pull request by kaltepeter**
- Convert blue ocean icons to jenkins icons for the pipeline graph
- update the skipped icon
- use dynamic imagesurl var

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

image

I am not sure if new tests are needed or if visuals are tested. 

Fixes #11 
Fixes #173

### Aborted, Running
Before:
https://user-images.githubusercontent.com/5103752/197560337-10e6ce1e-ea9b-469a-8d3c-5eb5d19a4628.mov

After: 
https://user-images.githubusercontent.com/5103752/197560378-84666132-aa3c-46ad-a472-34508ccae722.mov

### Success, Paused, Unstable
Before:
https://user-images.githubusercontent.com/5103752/197560548-f177c19f-6bb8-4be0-b731-408b70a7ce3d.mov

After:
https://user-images.githubusercontent.com/5103752/197560608-361d3094-20ca-483a-8807-732c8a2950ce.mov

### Unknown icons
Before:
image

After:
image

### CODE REVIEW

File: src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx [hunk 1]
```diff
@@ -15,122 +13,160 @@ const questionMarkPath =
...
-const crossPoints =
-  "4.67 -3.73 3.73 -4.67 0 -0.94 -3.73 -4.67 -4.67 -3.73 -0.94 0 -4.67 3.73 -3.73 4.67 0 0.94 " +
-  "3.73 4.67 4.67 3.73 0.94 0";
-
 interface Props {
   result: Result;
   radius: number;
 }
 
+const getImagesPath = () => `${document.head.dataset.imagesurl}`;
```
Comment (kaltepeter) [inline src/main/frontend/pipeline-graph-view/pipeline-graph/main/support/SvgStatus.tsx:21]: This should resolve the issue with https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/173

I was having a hard time testing this locally, it does work on the local server as is, but I wanted to test with a custom path and had no luck.

**Review by timja — APPROVED** [review]
Thanks for the fixup!
