### PR TITLE
Memoize `ConsoleLine`

### LINKED ISSUE #823: Up and down arrows move around during running build (page jumps a bit too)
### Reproduction steps

```groovy
node {
    stage('Checkout') {
        sh "git clone https://github.com/jenkinsci/jenkins"
    }
    
    stage('Build') {
        dir('jenkins') {
          sh "mvn clean install"
        }
    }
}
```

Watch a running build in the Build stage

### Expected Results

Arrows stay in same place, page doesn't move around

### Actual Results

https://github.com/user-attachments/assets/13385be7-14ea-4221-835a-299350c6b6a2

Arrows move up and down
Page can sometimes flash a little bit or jump a bit

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by basil**
A minor performance improvement, not enough to fix fully #823, but enough to be measurable in profiling so I thought I would submit it. See [React documentation](https://react.dev/reference/react/memo).

### Testing done

With

```tsx
diff --git a/src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx b/src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
index 7db8a20..87aefab 100644
--- a/src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
+++ b/src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx
@@ -29,6 +29,8 @@ export const ConsoleLine = (props: ConsoleLineProps) => {
     );
   }, []);
 
+  console.log(`Rendering console line ${props.stepId}-${props.lineNumber}`);
+
   return (
     <pre
       style={{ background: "none", border: "none" }}
```

I saw that previous lines were being re-rendered every time a new line appeared. With this PR, only new lines are rendered, which drastically reduced the number of log statements I saw from thousands to several hundred.

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

File: src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ declare global {
 }
 
 // Console output line
-export const ConsoleLine = (props: ConsoleLineProps) => {
+export const ConsoleLine = memo(function ConsoleLine(props: ConsoleLineProps) {
```
Comment (basil) [inline src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx:20]: After wrapping the component with `memo`, the resulting component's name was not automatically inferred, causing ESLint to flag a "missing `displayName`" error. By defining the component with a named function rather than the arrow syntax, React infers the `displayName` automatically.

Comment (felipecrs) [reply src/main/frontend/pipeline-console-view/pipeline-console/main/ConsoleLine.tsx:20]: +1. That's the exact same thing I did [here](https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/669/files#diff-ca4cd804cdacd00e239767848d64326cf03dd60b5518bc2abdcfe5fde64e1c93R96):

image
