### PR TITLE
Revert adding unneeded permission checks

### LINKED ISSUE #916: Can't display MultiPipelineGraphView for non-admin users
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.504.1
OS: Windows Server 2022 - 10.0
Java: 17.0.15 - Azul Systems, Inc. (OpenJDK 64-Bit Server VM)
---
PrioritySorter:863.v4a_b_974a_5d042
TestComplete:2.9.2
ansicolor:1.0.6
antisamy-markup-formatter:173.v680e3a_b_69ff3
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
apache-httpcomponents-client-5-api:5.5-150.veb_76e719855b_
asm-api:9.8-135.vb_2239d08ee90
azure-credentials:357.v6447d38fb_007
azure-keyvault:282.v43b_691a_13d19
azure-sdk:223.vff769b_ce66b_b_
badge:2.8
bootstrap5-api:5.3.7-1
bouncycastle-api:2.30.1.80-261.v00c0e2618ec3
branch-api:2.1233.vfb_6b_2b_3ed499
build-failure-analyzer:2.5.5
build-name-setter:2.5.0
build-timeout:1.38
build-timestamp:1.1.0
build-user-vars-plugin:195.v8c35f9d5c3dc
buildresult-trigger:1.01
buildtriggerbadge:251.vdf6ef853f3f5
caffeine-api:3.2.2-178.v353b_8428ed56
checks-api:373.vfe7645102093
cloudbees-folder:6.1036.vb_94fd035b_287
collapsing-console-sections:1.11.0
command-launcher:123.v37cfdc92ef67
commons-compress-api:1.27.1-3
commons-lang3-api:3.18.0-98.v3a_674c06072d
commons-text-api:1.13.1-176.v74d88f22034b_
conditional-buildstep:1.5.0
configuration-as-code:1971.vf9280461ea_89
copyartifact:770.va_6c69e063442
credentials:1415.v831096eb_5534
credentials-binding:696.v256688029804
custom-markup-formatter:39.v291c115db_c4d
dark-theme:524.vd675b_22b_30cb_
dashboard-view:2.537.v5132851f6ca_f
data-tables-api:2.3.2-3
display-url-api:2.209.v582ed814ff2f
durable-task:587.v84b_877235b_45
echarts-api:5.6.0-5
eddsa-api:0.3.0.1-19.vc432d923e5ee
editable-choice:71.v02a291ebbe45
emoji-symbols-api:16.0-26.v9818ff7423f0
envinject:2.926.v69c9b_3896a_96
envinject-api:1.235.va_14c74f8f487
exclusive-execution:0.8
external-monitor-job:223.vb_fddcf42c9b_3
extra-columns:1.27
font-awesome-api:6.7.2-1
generic-webhook-trigger:2.3.1
git:5.7.0
git-client:6.2.0
git-parameter:444.vca_b_84d3703c2
github-api:1.321-488.v9b_c0da_9533f8
groovy:497.v7b_061a_a_de65d
groovy-label-assignment:1.2.0
groovy-postbuild:272.v52a_03efb_8653
gson-api:2.13.1-139.v4569c2ef303f
htmlpublisher:427
http_request:1.20
instance-identity:203.v15e81a_1b_7a_38
ionicons-api:88.va_4187cb_eddf1
jackson2-api:2.19.2-408.v18248a_324cfe
jakarta-activation-api:2.1.3-2
jakarta-mail-api:2.1.3-2
javadoc:327.vdfe586651ee0
javax-activation-api:1.2.0-8
javax-mail-api:1.6.2-11
jaxb:2.3.9-133.vb_ec76a_73f706
jdk-tool:83.v417146707a_3d
jfrog:1.5.8
job-dsl:1.93
jobConfigHistory:1330.vcb_8320ea_cdb_e
joda-time-api:2.14.0-127.v7d9da_295a_d51
jquery:1.12.4-3
jquery3-api:3.7.1-3
json-api:20250517-153.vc8a_a_d87c0ce3
json-path-api:2.9.0-148.v22a_7ffe323ce
junit:1335.v6b_a_a_e18534e1
leastload:62.vfa_8830902733
locale:587.v7b_843928a_719
lockable-resources:1408.vb_7d1f371781d
mailer:509.vc54d23fc427e
matrix-auth:3.2.6
matrix-project:849.v0cd64ed7e531
metrics:4.2.32-476.v5042e1c1edd7
mina-sshd-api-common:2.15.0-161.vb_200831a_c15b_
mina-sshd-api-core:2.15.0-161.vb_200831a_c15b_
monitoring:2.5.0
multibranch-scan-webhook-trigger:1.0.11
naginator:1.504.vfc3736332f16
netty-api:4.1.118.Final-9.v776038d601a_7
nodelabelparameter:759.vb_b_e95db_f3251
okhttp-api:4.11.0-189.v976fa_d3379d6
parameterized-trigger:859.vb_e3907a_07a_16
pipeline-agent-build-history:100.v42603a_8d8477
pipeline-build-step:571.v08a_fffd4b_0ce
pipeline-graph-analysis:241.vc3d48fb_b_2582
pipeline-graph-view:603.v23e636851f81
pipeline-groovy-lib:752.vdddedf804e72
pipeline-input-step:527.vd61b_1d3c5078
pipeline-milestone-step:138.v78ca_76831a_43
pipeline-model-api:2.2255.v56a_15e805f12
pipeline-model-definition:2.2255.v56a_15e805f12
pipeline-model-extensions:2.2255.v56a_15e805f12
pipeline-rest-api:2.38
pipeline-stage-step:322.vecffa_99f371c
pipeline-stage-tags-metadata:2.2255.v56a_15e805f12
pipeline-utility-steps:2.19.0
plain-credentials:199.v9f8e1f741799
plugin-util-api:6.1.0
postbuild-task:78.v24529f1f5cdb_
powershell:2.3
preSCMbuildstep:115.vf9808414429d
prism-api:1.30.0-1
project-description-setter:1.2
prometheus:819.v50953a_c560dd
purge-build-queue-plugin:125.v09ee2147746f
rebuild:338.va_0a_b_50e29397
resource-disposer:0.25
role-strategy:785.v8d262df0f607
run-condition:243.v3c3f94e46a_8b_
saml:4.568.v78a_9a_db_8dc9b_
scm-api:704.v3ce5c542825a_
script-security:1373.vb_b_4a_a_c26fa_00
sidebar-link:2.4.2
simple-theme-plugin:211.v5424a_5510e47
skip-certificate-check:50.vcfa_cdb_b_27312
snakeyaml-api:2.3-125.v4d77857a_b_402
ssh-credentials:359.v2191c4cf635f
sshd:3.372.v5d04a_e92d8cf
structs:350.v3b_30f09f2363
text-file-operations:1.3.2
text-finder:1.32
theme-manager:313.v8657a_a_7692cb_
timestamper:1.30
token-macro:444.v52de7e9c573d
trilead-api:2.209.v0e69b_c43c245
uno-choice:2.8.4-SNAPSHOT (private-a592dd8d-grno)
variant:70.va_d9f17f859e0
view-job-filters:401.va_809f6a_b_0c26
workflow-aggregator:608.v67378e9d3db_1
workflow-api:1380.ve03e7a_63d139
workflow-basic-steps:1079.vce64b_a_929c5a_
workflow-cps:4169.vb_7e492a_1c7b_e
workflow-durable-task-step:1434.v1b_595c29ddd7
workflow-job:1540.v295eccc9778f
workflow-multibranch:806.vb_b_688f609ee9
workflow-scm-step:437.v05a_f66b_e5ef8
workflow-step-api:704.ve4f0967e98fa_
workflow-support:968.v8f17397e87b_8
ws-cleanup:0.48
xtrigger-api:1.2
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I use Windows for both controller and agents. None of the agents where involved in the issue

### Reproduction steps

1. Create one admin and non-admin user in role-based system authorization
2. Give non-admin user full access to one project 
3. Navigate to project, user sees multipipeline-graph-view in project page
4. Update pipeline-graph-view from 521.v799963fd568a_ to 603.v23e636851f81
5. Navigate to project, user con't see multipipeline-graph-view in project page 

### Expected Results

User should be able to see multipipeline-graph-view in project page when has read permissions to the job/project

### Actual Results

User does not see multipipeline-hraph-view in project, even tough it has full access to the project. I tried to ellavate more access rights, but that didn't help out, only assigning admin rights helps in this case.

Image

In the web console I saw that we get 403 on the /runs

Image

when I click on it, I get following screenshot 

Image

### Anything else?

_No response_

### Are you interested in contributing a fix?

Unfortunately I can't contribute to this right now.

### PR DESCRIPTION
**Pull request by lewisbirks**
Fixes #916. Everything was working fine before, these checks were added to satisfy warnings and local testing was fine.

### Testing done

`mvn clean verify`

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

**Review by janfaracik — APPROVED** [review]

File: src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java [hunk 1]
```diff
@@ -114,8 +114,6 @@ private JSONObject getSteps(String nodeId) {
     @GET
     @WebMethod(name = "allSteps")
     public void getAllSteps(StaplerRequest2 req, StaplerResponse2 rsp) throws IOException, ServletException {
-        run.checkPermission(Item.READ);
```
Comment (mawinter69) [inline src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java:117]: The correct implementation would be `run.getParent().checkPermission(Item.READ)`

File: src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java [hunk 2]
```diff
@@ -71,7 +71,6 @@ public boolean isShowStageDurations() {
     @GET
     @WebMethod(name = "runs")
     public void getRuns(StaplerRequest2 req, StaplerResponse2 rsp) throws ServletException, IOException {
-        target.checkPermission(Permission.READ);
```
Comment (mawinter69) [inline src/main/java/io/jenkins/plugins/pipelinegraphview/multipipelinegraphview/MultiPipelineGraphViewAction.java:74]: Correct would be `target.checkPermission(Item.READ);`

File: src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java (hunk 1 above)
Comment (lewisbirks) [reply src/main/java/io/jenkins/plugins/pipelinegraphview/consoleview/PipelineConsoleViewAction.java:117]: Ahh so the permission check needed to be against the job rather than the run itself
