### PR TITLE
fix: don't cache blocks when part of an active node

### LINKED ISSUE #1252: Pipeline succeeded but some steps are still running
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 Jenkins: 2.555.1
OS: Linux - 3.10.0-1160.el7.x86_64
Java: 25.0.1 - Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM)
---
ansicolor:536.v13fa_b_860c267
antisamy-markup-formatter:173.v680e3a_b_69ff3
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
asm-api:9.9.1-189.vb_5ef2964da_91
authentication-tokens:1.144.v5ff4a_5ec5c33
authorize-project:2.0.0
bootstrap5-api:5.3.8-1024.v127320880c60
bouncycastle-api:2.30.1.84-291.v9f17b_21896e2
branch-api:2.1280.v0d4e5b_b_460ef
build-timeout:1.40
caffeine-api:3.2.3-194.v31a_b_f7a_b_5a_81
checks-api:402.vca_263b_f200e3
cloudbees-folder:6.1100.ve9eed61d16c4
commons-compress-api:1.28.0-3
commons-lang3-api:3.20.0-109.ve43756e2d2b_4
commons-text-api:1.15.0-218.va_61573470393
config-file-provider:1006.vc7366c201f57
credentials:1502.v5c95e620ddfe
credentials-binding:719.v80e905ef14eb_
data-tables-api:2.3.7-1558.vf82fa_133ce1c
display-url-api:2.217.va_6b_de84cc74b_
docker-commons:472.vee120e23d3a_c
docker-workflow:634.vedc7242b_eda_7
durable-task:664.v2b_e7a_dfff66c
echarts-api:6.0.0-1281.vd3d21a_1ca_cb_4
eddsa-api:0.3.0.1-29.v67e9a_1c969b_b_
font-awesome-api:7.2.0-983.v3f63c34eddb_9
git:5.10.1
git-client:6.6.0
git-parameter:462.vdcf3df2ed2ca_
gitlab-plugin:1.9.13
gson-api:2.14.0-201.v8eefe5515533
instance-identity:203.v15e81a_1b_7a_38
ionicons-api:94.vcc3065403257
jackson-annotations2-api:2.21-7.v4777a_f3a_a_d47
jackson2-api:2.21.2-436.v29efdb_7418ff
jackson3-api:3.1.2-73.v3e5485d8b_148
jakarta-activation-api:2.1.4-1
jakarta-mail-api:2.1.5-1
jakarta-xml-bind-api:4.0.6-12.vb_1833c1231d3
javax-activation-api:1.2.0-8
jaxb:2.3.9-143.v5979df3304e6
jersey3-api:3.1.11-4.v77818819c2e1
job-dsl:3654.vdf58f53e2d15
joda-time-api:2.14.1-187.vdf2def02b_8a_1
jquery3-api:3.7.1-682.vfa_cdce169929
jsch:0.2.16-95.v3eecb_55fa_b_78
json-api:20251224-185.v0cc18490c62c
json-path-api:3.0.0-218.vcd4dd1355de2
junit:1403.vd9d1413fd205
lark-notice:2.1.7
lockable-resources:1509.va_6b_5b_5cb_0b_40
mailer:534.v1b_36f5864073
mapdb-api:1.0.9-44.va_1e1310c9118
matrix-project:870.v9db_fcfc2f45b_
metrics:4.2.37-494.v06f9a_939d33a_
mina-sshd-api-common:2.16.0-167.va_269f38cc024
mina-sshd-api-core:2.16.0-167.va_269f38cc024
nodejs:1.6.6
pipeline-build-step:584.vdb_a_2cc3a_d07a_
pipeline-graph-analysis:254.v0f63a_a_447dca_
pipeline-graph-view:867.vece2ec789435
pipeline-groovy-lib:797.v90ea_a_9b_e45a_0
pipeline-input-step:551.vdff487c5998c
pipeline-milestone-step:152.v6e22b_8cfc66c
pipeline-model-api:2.2277.v00573e73ddf1
pipeline-model-definition:2.2277.v00573e73ddf1
pipeline-model-extensions:2.2277.v00573e73ddf1
pipeline-rest-api:2.41
pipeline-stage-step:345.va_96187909426
pipeline-stage-tags-metadata:2.2277.v00573e73ddf1
pipeline-stage-view:2.41
pipeline-utility-steps:2.20.0
plain-credentials:199.v9f8e1f741799
plugin-util-api:7.1330.v47b_46ee2047a_
prism-api:1.30.0-723.v97277866cece
publish-over:238.v1db_583004c9b_
publish-over-ssh:390.vb_f56e7405751
resource-disposer:0.25
scm-api:728.vc30dcf7a_0df5
script-security:1399.ve6a_66547f6e1
snakeyaml-api:2.5-149.v72471e9c6371
snakeyaml-engine-api:3.0.1-5.vd98ea_ff3b_92e
ssh-agent:396.vcc7d84e622ec
ssh-credentials:372.va_250881b_08cd
ssh-slaves:3.1097.v868116049892
structs:362.va_b_695ef4fdf9
timestamper:1.30
token-macro:477.vd4f0dc3cb_cf1
trilead-api:2.284.v1974ea_324382
uno-choice:2.8.9
variant:70.va_d9f17f859e0
woodstox-core-api:7.1.1-1.v4d297985f397
workflow-aggregator:608.v67378e9d3db_1
workflow-api:1413.v2ff1a_5e720fa_
workflow-basic-steps:1098.v808b_fd7f8cf4
workflow-cps:4303.v8fa_2a_581f0a_6
workflow-durable-task-step:1475.ved562f6ec8b_3
workflow-job:1571.vb_423c255d6d9
workflow-multibranch:821.vc3b_4ea_780798
workflow-scm-step:466.va_d69e602552b_
workflow-step-api:724.v538c2362b_dfb_
workflow-support:1015.v785e5a_b_b_8b_22
ws-cleanup:0.49
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

CentOS Linux release 7.9.2009 (Core)

### Reproduction steps

<details>
  <summary>Example pipeline</summary>

  ```text
pipeline {
    agent {
        label 'backend'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
        disableConcurrentBuilds()
    }

    environment {
        xxx
    }

    parameters {
        gitParameter(
            xxx
        )
    }

    stages {
        stage('Init config') {
            steps {
                script {
                    xxx
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: xxx
            }
        }

        stage('Package & Build & Deploy') {
            tools {
                xxx
            }

            steps {
                script {
                    xxx
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
  ```

</details>

### Expected Results

All steps should be marked as `Successful` after completion.

### Actual Results

Some steps remain in the `Running` state even after the post-action phase has completed, and the timer keeps increasing during this state. This behavior occurs intermittently and is not consistently reproducible.

example 1:
Image

example 2:
Image

### Anything else?

This issue may have started occurring after the plugin upgrade. I have not encountered this behavior before.

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by lewisbirks**
Fixes #1252.

### Testing done

Tested locally with:

<details>
<summary>PIpeline</summary>

```groovy
pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '30'))
        timestamps()
    }

    environment {
        APP_NAME = 'demo-app'
        BUILD_TARGET = 'release'
    }

    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Branch to build')
        choice(name: 'MODE', choices: ['fast', 'slow'], description: 'Build mode')
    }

    stages {
        stage('Init config') {
            steps {
                script {
                    echo "Init config for ${params.BRANCH} in ${params.MODE} mode"
                    sleep time: 1, unit: 'SECONDS'
                }
            }
        }

        stage('Checkout') {
            steps {
                echo "Pretending to git checkout ${params.BRANCH}"
                sleep time: 1, unit: 'SECONDS'
            }
        }

        stage('Package & Build & Deploy') {
            steps {
                script {
                    echo "Building ${env.APP_NAME}"
                    sh 'echo build step 1 && sleep 1'
                    sh 'echo build step 2 && sleep 1'
                    sh 'echo build step 3 && sleep 1'
                    echo "Deploying ${env.APP_NAME}"
                }
            }
        }
    }

    post {
        always {
            echo 'Post: cleaning workspace'
        }
    }
}

```

</details>

Before could reproduce it occasionally, can't reproduce it anymore.

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

**Review by timja — APPROVED** [review]
Tested, LGTM, thanks

File: src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphViewCache.java [hunk 1]
```diff
@@ -37,7 +37,7 @@
  */
 public class PipelineGraphViewCache {
 
-    public static final int SCHEMA_VERSION = 1;
+    public static final int SCHEMA_VERSION = 2;
```
Comment (timja) [inline src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineGraphViewCache.java:40]: incremented this to invalidate existing cached versions that could be bugged

(likely will still be cached in the browser though)

**Comment by guolunwei** [comment]
After upgrading to version `872.vf5b_ec277ffb_b_`, I tested the pipeline mentioned above locally.

The first 5 runs completed successfully. However, on the 6th run, the pipeline behaved unexpectedly:

- The stages remain stuck in the "Running" state
- The reported start time is incorrect

<details>
  <summary>Console</summary>

```shell
Started by user [admin](http://192.168.1.10:8080/user/admin)
Running as [admin](http://192.168.1.10:8080/user/admin)
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [Jenkins](http://192.168.1.10:8080/computer/(built-in)/) in /home/admin/jenkins/workspace/test
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Init config)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
10:37:36  Init config for main in fast mode
[Pipeline] sleep
10:37:36  Sleeping for 1 sec
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] echo
10:37:38  Pretending to git checkout main
[Pipeline] sleep
10:37:38  Sleeping for 5 sec
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Package & Build & Deploy)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
10:37:44  Building demo-app
[Pipeline] sh
10:37:44  + echo build step 1
10:37:44  build step 1
10:37:44  + sleep 1
[Pipeline] sh
10:37:45  + echo build step 2
10:37:45  build step 2
10:37:45  + sleep 1
[Pipeline] sh
10:37:47  + echo build step 3
10:37:47  build step 3
10:37:47  + sleep 1
[Pipeline] echo
10:37:48  Deploying demo-app
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
10:37:49  Post: cleaning workspace
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
``` 

</details>

<details>
  <summary>Stages</summary>

image

</details>

Could you confirm whether this fix is expected to resolve this issue? Or is there any additional configuration required?

Thanks.

**Comment by timja** [comment]
It is expected to damn, I tried ~15 or so times and it didn't reproduce for me, I'll re-open the issue
